In [ ]:
!pip install numpy

In [25]:
import numpy as np

In [ ]:
#create a 1D array
x = [1,2,3,4,5]
type(x)

list

In [ ]:
a = np.array(x)
a
type(a)

numpy.ndarray

In [ ]:
#Create a 2D array
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Methods on numpy
#1.shape
b.shape

(2, 3)

In [ ]:
#2.size ----return element present in
b.size

6

In [ ]:
#3. Transpose----It return an array by swapping rows to column and vise-versa
b.T     # T --> Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#4. ndim-----It return dimension of an array
b.ndim    # return type of array

2

In [ ]:
a.ndim

1

In [ ]:
#5. Reshape-----
b.reshape()

ValueError: cannot reshape array of size 6 into shape (1,)

In [ ]:
a.reshape(5,1)

In [ ]:
# Functions in Numpy
#1. concatenate--
x = np.array([1,2,3,4,5,6]).reshape(2,3)
x

In [ ]:
y = np.array([7,8,9,10,11,12]).reshape(2,3)
y

In [ ]:
np.concatenate((x,y),axis=0)

In [ ]:
np.concatenate((x,y),axis=1)

In [ ]:
#2. vstack---This is used to stack sequence vertically
np.vstack((x,y))

NameError: name 'y' is not defined

In [ ]:
#3. hstack---This is used to stack sequence horizontally
np.hstack((x,y))

NameError: name 'y' is not defined

In [ ]:
#4. append ----it is used toa dd the values to string array
#np.append(array,values,axis=none)
c = np.array([11,12,13,14,15,16]).reshape(2,3)

In [28]:
np.append(c,y)

NameError: name 'y' is not defined

In [29]:
#arange:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [31]:
#linspace
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [32]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [34]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [35]:
#Random.rand------------ It returns an array of specified shape with random values
np.random.rand(10)


array([0.08207245, 0.55489605, 0.50079759, 0.34015979, 0.36641805,
       0.70706096, 0.77677912, 0.13354636, 0.09158016, 0.42128578])

In [36]:
np.random.rand(3,3)

array([[0.51205988, 0.85988738, 0.06519787],
       [0.41565144, 0.06071703, 0.22589338],
       [0.85509271, 0.39264603, 0.99478366]])

In [37]:
np.random.rand(3,2,2)    # (no. of matrix,rows,col)


array([[[0.05800916, 0.1757764 ],
        [0.11169949, 0.01097947]],

       [[0.34283991, 0.87793174],
        [0.14029176, 0.64920757]],

       [[0.24510955, 0.67245451],
        [0.69240275, 0.6944963 ]]])

In [38]:
#Random.randn------------ It returns an array of specified shape with random values with -ve
np.random.randn(5)

array([-0.31662365,  0.06659699,  0.98322806,  0.29511386, -1.07027964])

In [39]:
np.random.randn(3,4)

array([[-1.22895413, -1.0917074 , -0.21735025,  0.98090167],
       [ 0.22495211,  1.11651077,  0.92340497,  0.66182387],
       [-0.16570547, -0.45786806,  0.00569212,  0.48759252]])

In [40]:
np.random.randn(2,3,2)

array([[[ 0.34508927,  0.26280594],
        [ 0.07262788,  1.26539504],
        [-0.09087538,  1.69852707]],

       [[ 1.15684822, -0.5368933 ],
        [-0.93205783,  1.41113033],
        [ 1.03008625, -1.2663576 ]]])

In [42]:
#slicing and indexing
#1.index position-->
a = np.arange(21,31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
a[2]

23

In [46]:
a[-2]

29

In [47]:
a[1:6]

array([22, 23, 24, 25, 26])

In [48]:
a[:7]

array([21, 22, 23, 24, 25, 26, 27])

In [50]:
a[5:]

array([26, 27, 28, 29, 30])

In [51]:
a[:]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
a[::2]

array([21, 23, 25, 27, 29])

In [54]:
##  Slicing and indexing on 2D array------>

x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
x[0,1]

2

In [56]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
x[1,2]

6

In [58]:
x[1:,0:2]

array([[4, 5],
       [7, 8]])

In [59]:
x[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
### Vectorization---------------->Used to perform arithmetic operations each and every element


In [61]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
b+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [63]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
b/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [65]:
b>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
b%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
#### masking --> It returns all values > 3 instead of returning boolean values

In [67]:
mask = b > 3
b[mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [68]:
b[b%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
## selection of values in an array------>

In [ ]:
names = np.array(['ram','sam','jacky','harry','ram'], dtype='<us')